// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! FFI entry point for the FlightSQL ADBC driver.
//!
//! When the `ffi` feature is enabled and the crate is compiled as a `cdylib`,
//! this module exports two C-ABI symbols via the [`adbc_ffi::export_driver!`] macro:
//!
//! - **`AdbcFlightSqlDriverInit`** — Primary entry point. The C driver manager calls
//!   this with pointers to an ADBC version integer, a driver struct, and an error
//!   struct. On success, it writes the full FFI function table
//!   (`FFI_AdbcDriver`) to the driver pointer. On failure, it writes error details
//!   to the error out-parameter.
//!
//! - **`AdbcDriverInit`** — Fallback/alias symbol. Delegates directly to
//!   `AdbcFlightSqlDriverInit` via the macro-generated wrapper. This is a
//!   convenience for driver managers that search for the shorter symbol name.
//!
//! ## ADBC Version
//!
//! The driver targets ADBC protocol version **1.1.0** (`ADBC_VERSION_1_1_0`,
//! `AdbcVersion::V110`). The `export_driver!` macro validates at runtime that
//! the caller passes `ADBC_VERSION_1_1_0` in the version integer; if the
//! version does not match, the driver returns `ADBC_STATUS_NOT_IMPLEMENTED`.
//!
//! ## Driver Initialization
//!
//! When the driver manager calls `DatabaseInit`, the exported functions
//! instantiate [`FlightSqlDriver`] via `Default::default()`. This creates a
//! fresh driver with no tokio runtime handle — each subsequent `DatabaseNew`
//! call spawns a new multi-threaded tokio runtime for that database. Drivers
//! created via [`FlightSqlDriver::new`] (with an existing runtime handle)
//! share the handle across databases instead.
//!
//! ## Panic Safety
//!
//! All `extern "C"` functions generated by the macro are wrapped in
//! [`std::panic::catch_unwind`] (see driver_exporter.rs `catch_panic`).
//! If a Rust panic occurs inside the driver:
//!
//! - The panic is caught at the FFI boundary — it **never** unwinds into C.
//! - A global `POISON` atomic flag is set, which prevents further calls
//!   to the driver until the library is reloaded.
//! - The error out-parameter receives [`adbc_core::error::Status::Internal`] with an
//!   appropriate message.
//!
//! ## Thread Safety
//!
//! The ADBC specification allows serialized access to objects from multiple
//! threads; concurrent access is not supported. The exporter wraps all
//! driver-managed objects in [`std::sync::Mutex`] or stores them in
//! `HashMap`-based registries keyed by opaque C pointers. Ownership
//! transfer between C and Rust follows ADBC's pointer-out conventions:
//! the driver allocates, the caller frees via the corresponding release
//! function.

use crate::FlightSqlDriver;

// Invoke the `export_driver!` macro from `adbc_ffi` to generate the two
// C-ABI entry points.
//
// ## Generated symbols
//
//   `AdbcFlightSqlDriverInit(int version, void* driver, struct AdbcError* error)`
//     Primary entry point for ADBC driver managers. Validates version against
//     `ADBC_VERSION_1_1_0`, checks pointer validity, and writes the
//     `FFI_AdbcDriver` function table. Returns `ADBC_STATUS_OK` on success or
//     an error status via the error out-parameter.
//
//   `AdbcDriverInit(int version, void* driver, struct AdbcError* error)`
//     Fallback/alias generated by the macro. Equivalent to
//     `AdbcFlightSqlDriverInit` — provided for driver managers that probe
//     for the common `AdbcDriverInit` symbol.
//
// Both functions:
// - Validate the ADBC version (must be 1.1.0)
// - Use `catch_panic` to prevent Rust panics from unwinding into C
// - Instantiate `FlightSqlDriver` via `Default::default()` on first
//   `DatabaseInit` call
adbc_ffi::export_driver!(AdbcFlightSqlDriverInit, FlightSqlDriver);
